### ISSUE TITLE
error generate goundntruth

### ISSUE THREAD

**Issue by Anislar** [surajdakua/Crowd-Counting-Using-Pytorch#2]
(base) C:\Users\larguet\Desktop\Crowd-Counting-Using-Pytorch-master>python GenerateGroudnTruth.py
C:/Users/larguet/Desktop/Crowd-Counting-Using-Pytorch-master/shanghaitech_part_B/train_data/images\IMG_1.jpg
Traceback (most recent call last):
  File "C:\Users\larguet\Anaconda3.1\lib\site-packages\scipy\io\matlab\mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/larguet/Desktop/Crowd-Counting-Using-Pytorch-master/shanghaitech_part_B/train_data/ground-truth\\GT_IMG_1.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GenerateGroudnTruth.py", line 65, in <module>
    mat = io.loadmat(img_path.replace('.jpg','.mat').replace('images','ground-truth').replace('IMG_','GT_IMG_'))
  File "C:\Users\larguet\Anaconda3.1\lib\site-packages\scipy\io\matlab\mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "C:\Users\larguet\Anaconda3.1\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\larguet\Anaconda3.1\lib\site-packages\scipy\io\matlab\mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "C:\Users\larguet\Anaconda3.1\lib\site-packages\scipy\io\matlab\mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/larguet/Desktop/Crowd-Counting-Using-Pytorch-master/shanghaitech_part_B/train_data/ground-truth\\GT_IMG_1.mat'

help ?

**Comment by surajdakua** [comment]
Check the directory path. It seems you have given wrong path to the directory.

**Comment by Anislar** [comment]
please when i try to train the model what's arg should i put ? and thank you mr SURAJDAKIA
